# Generated by Django 3.1.7 on 2021-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20210305_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the Link Above to Read Post', max_length=255),
        ),
    ]
