# Generated by Django 3.1.7 on 2021-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_auto_20210410_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isSuggested',
            field=models.CharField(choices=[('HighlySuggested', 'HighlySuggested'), ('Normal', 'Normal')], max_length=30),
        ),
    ]
